version: '3'
services:
  web:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
    ports:
      - "8000:8000"
    environment:
      - VERLOOP_DEBUG
      - FLASK_ENV